name 'moodle'
maintainer 'Marcus Fabriczy'
maintainer_email 'marcusfabriczy@gmail.com'
license 'all_rights'
description 'Installs/Configures Redhat stack in preperation to install Moodle'
long_description 'Installs/Configures Redhat stack in preperation to install Moodle'
version '0.1.0'

depends 'postgresql', '~> 5.1.0'
depends 'database', '~> 6.1.1'
